### ISSUE TITLE
Could you provide show me your email?

### ISSUE THREAD

**Issue by GabrielLin** [h404bi/wende#1]
Dear hanibi,
I am a NLP person working at Guangzhou too. I like your wende project. Could you give me your email? I hope I can talk with you in details by email.

**Comment by h404bi** [comment]
Hi, I don't play with the project (or NLP) for some time, but if you still want to have a talk to me about something, you could send e-mail to <my_github_id>#gmail.com.

**Comment by GabrielLin** [comment]
OK，thanks.
